source: .
destination: _site
include: ['.htaccess']
future: true

title: Andreas Eracleous
tagline: 'Andreas Eracleous'
# Short bio or description (displayed in the header)
description: Andreas is a freelance Front-end Web Developer who is expert in converting PSD to Bootstrap website, HTML, CSS, JavaScript code and he is experienced with optimizing website load speed. Also, he is available for development jobs for helping you with your website and progressive web app.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/img/about/andreas.jpg
email: contact@andreaseracleous.com

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
social-links:
  dribbble:
  email: contact@andreaseracleous.com
  facebook: https://www.facebook.com/andrew.eracleous
  flickr:
  github: https://github.com/AndreasEracleous
  instagram: https://www.instagram.com/sp0_0ky/
  linkedin: https://cy.linkedin.com/in/andreaseracleous/
  pinterest:
  rss: https://andreaseracleous.com/feed
  twitter: https://twitter.com/AndrewEracleous
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

twitter:
  username: AndrewEracleous

social:
  name: Andreas Eracleous
  links:
    - https://twitter.com/AndrewEracleous
    - https://www.facebook.com/andrew.eracleous
    - https://cy.linkedin.com/in/andreaseracleous
    - https://plus.google.com/+AndreasEracleous
    - https://github.com/AndreasEracleous
    - https://www.instagram.com/sp0_0ky

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: freelance-front-end-web-developer

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-45366498-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://andreaseracleous.com"

# development: bundle exec jekyll serve --incremental
# production : JEKYLL_ENV=production bundle exec jekyll serve --incremental
environment: development

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/blog/page:num/"
sass:
  sass_dir: assets/css
  style: compressed
  
tags:

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-tagging

#github: 
#repo: https://github.com/AndreasEracleous/andreaseracleous.github.io/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
#  - CNAME





